version: '3'
services:
  aapplication:
    build: ./
    image: giovane1999/php-nginx
    container_name: clean_application
    volumes:
      - ./:/var/www/html
    ports:
      - "80:80"
    networks:
      - clean_network
    depends_on:
      - database
  database:
    image: mysql:latest
    command: "--default-authentication-plugin=mysql_native_password"
    container_name: clean_database
    restart: always
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: clean_arch
      MYSQL_USER: giovane
      MYSQL_PASSWORD: enavoig
    volumes:
      - ./docker/database:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    networks:
      - clean_network
networks:
  clean_network:
    driver: bridge
